// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID        uuid.UUID          `json:"id"`
	UserID    string             `json:"user_id"`
	ItemID    string             `json:"item_id"`
	Quantity  int32              `json:"quantity"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Outbox struct {
	ID        uuid.UUID          `json:"id"`
	EventType string             `json:"event_type"`
	Payload   []byte             `json:"payload"`
	Published bool               `json:"published"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
