// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (id, user_id, item_id, quantity, status)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE SET id = EXCLUDED.id
RETURNING id, user_id, item_id, quantity, status, created_at
`

type CreateOrderParams struct {
	ID       uuid.UUID `json:"id"`
	UserID   string    `json:"user_id"`
	ItemID   string    `json:"item_id"`
	Quantity int32     `json:"quantity"`
	Status   string    `json:"status"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.ID,
		arg.UserID,
		arg.ItemID,
		arg.Quantity,
		arg.Status,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ItemID,
		&i.Quantity,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getOrder = `-- name: GetOrder :one
SELECT id, user_id, item_id, quantity, status, created_at
FROM orders
WHERE id = $1
`

func (q *Queries) GetOrder(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ItemID,
		&i.Quantity,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :exec
INSERT INTO outbox (id, event_type, payload)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO NOTHING
`

type InsertOutboxEventParams struct {
	ID        uuid.UUID `json:"id"`
	EventType string    `json:"event_type"`
	Payload   []byte    `json:"payload"`
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertOutboxEvent, arg.ID, arg.EventType, arg.Payload)
	return err
}

const listUnpublishedOutboxEvents = `-- name: ListUnpublishedOutboxEvents :many
SELECT id, event_type, payload, published, created_at
FROM outbox
WHERE published = false
ORDER BY created_at
LIMIT $1
FOR UPDATE SKIP LOCKED
`

func (q *Queries) ListUnpublishedOutboxEvents(ctx context.Context, limit int32) ([]Outbox, error) {
	rows, err := q.db.Query(ctx, listUnpublishedOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Outbox
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.Payload,
			&i.Published,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEventPublished = `-- name: MarkOutboxEventPublished :exec
UPDATE outbox SET published = true WHERE id = $1
`

func (q *Queries) MarkOutboxEventPublished(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxEventPublished, id)
	return err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders SET status = $2 WHERE id = $1
`

type UpdateOrderStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.Exec(ctx, updateOrderStatus, arg.ID, arg.Status)
	return err
}
