// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	GetOrder(ctx context.Context, id uuid.UUID) (Order, error)
	InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error
	ListUnpublishedOutboxEvents(ctx context.Context, limit int32) ([]Outbox, error)
	MarkOutboxEventPublished(ctx context.Context, id uuid.UUID) error
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error
}

var _ Querier = (*Queries)(nil)
