// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Outbox struct {
	ID        uuid.UUID          `json:"id"`
	EventType string             `json:"event_type"`
	Payload   []byte             `json:"payload"`
	Published bool               `json:"published"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Product struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	PriceCents  int32              `json:"price_cents"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
