// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	GetProduct(ctx context.Context, id uuid.UUID) (Product, error)
	InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error
	ListUnpublishedOutboxEvents(ctx context.Context, limit int32) ([]Outbox, error)
	MarkOutboxEventPublished(ctx context.Context, id uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
