apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notification-worker
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Rishab-Kumar-R/tf-man.git
    targetRevision: main
    path: stampede/gitops/apps/notification-worker
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: stampede
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
